# SPDX-FileCopyrightText: 2024 Samuel Wu
#
# SPDX-License-Identifier: 0BSD

# Font
font_family family="Cascadia Code NF" features="+calt +ss01"
font_size 12

# Background
window_logo_path ~/Pictures/Terminal/FP/feli_miku_6.png
window_logo_position right
window_logo_alpha 0.5
window_logo_scale 100

# Layout
enabled_layouts splits,tall,*

# Terminal style
cursor_shape  beam
tab_bar_style powerline

# Report kitty as kitty since xterm-kitty is intentionally misleading
term kitty

# Keybinds
kitty_mod ctrl+shift

clear_all_shortcuts yes

# Clipboard
map --allow-fallback=shifted,ascii kitty_mod+c copy_to_clipboard
map --allow-fallback=shifted,ascii kitty_mod+v paste_from_clipboard

map --allow-fallback=shifted,ascii ctrl+insert copy_to_clipboard
map --allow-fallback=shifted,ascii shift+insert paste_from_selection

# Scrolling
map kitty_mod+up scroll_line_up smooth
map kitty_mod+down scroll_line_down smooth

map kitty_mod+page_up scroll_page_up
map kitty_mod+page_down scroll_page_down

map kitty_mod+home scroll_home
map kitty_mod+end scroll_end

# Search
map kitty_mod+/ search_scrollback

# Window
map --allow-fallback=shifted,ascii kitty_mod+n new_os_window
map --allow-fallback=shifted,ascii alt+f4 close_os_window

# Panes
map alt+shift+d launch --location=split
map alt+shift+h launch --location=hsplit
map alt+shift+v launch --location=vsplit

map --allow-fallback=shifted,ascii kitty_mod+w close_window

# Focus
map kitty_mod+] next_window
map kitty_mod+[ previous_window

map ctrl+left neighboring_window left
map ctrl+right neighboring_window right
map ctrl+up neighboring_window up
map ctrl+down neighboring_window down

# Moving
map alt+left move_window left
map alt+right move_window right
map alt+up move_window up
map alt+down move_window down

map --allow-fallback=shifted,ascii kitty_mod+f move_window_forward
map --allow-fallback=shifted,ascii kitty_mod+b move_window_backward

# Resize
map --allow-fallback=shifted,ascii kitty_mod+r start_resizing_window
map alt+shift+left resize_window narrower
map alt+shift+right resize_window wider
map alt+shift+up resize_window taller
map alt+shift+down resize_window shorter

# Tabs
map ctrl+tab next_tab
map ctrl+shift+tab previous_tab

map --allow-fallback=shifted,ascii kitty_mod+t new_tab
map --allow-fallback=shifted,ascii kitty_mod+q close_tab

map --allow-fallback=shifted,ascii kitty_mod+alt+t set_tab_title

map ctrl+alt+1 goto_tab 1
map ctrl+alt+2 goto_tab 2
map ctrl+alt+3 goto_tab 3
map ctrl+alt+4 goto_tab 4
map ctrl+alt+5 goto_tab 5
map ctrl+alt+6 goto_tab 6
map ctrl+alt+7 goto_tab 7
map ctrl+alt+8 goto_tab 8
map ctrl+alt+9 goto_tab 0

# Font Size
map ctrl+plus change_font_size all +2.0
map ctrl+minus change_font_size all -2.0
map ctrl+0 change_font_size all 0

# Misc
map kitty_mod+p command_palette

map f11 toggle_fullscreen
map alt+enter toggle_fullscreen

map --allow-fallback=shifted,ascii kitty_mod+u kitten unicode_input

map ctrl+, edit_config_file

map kitty_mod+escape kitty_shell window

map kitty_mod+delete clear_terminal reset active

map kitty_mod+k clear_terminal to_cursor_scroll active

# Windows Terminal Dark+ Theme
foreground #cccccc
background #1e1e1e

selection_foreground #000000
selection_background #ffffff

cursor            #808080
cursor_text_color #000000

color0 #000000
color8 #666666

color1 #cd3131
color9 #f14c4c

color2  #0dbc79
color10 #23d18b

color3  #e5e510
color11 #f5f543

color4  #2472c8
color12 #3b8eea

color5  #bc3fbc
color13 #d670d6

color6  #11a8cd
color14 #29b8db

color7  #e5e5e5
color15 #e5e5e5
