#!/usr/bin/env bash
# SPDX-FileCopyrightText: 2025 Samuel Wu
#
# SPDX-License-Identifier: 0BSD

# -e: exit on error
# -u: exit on unset variables
set -eu

if ! chezmoi="$(command -v chezmoi)"; then
  bin_dir="${HOME}/.local/bin"
  chezmoi="${bin_dir}/chezmoi"

  printf >&2 "Installing chezmoi to '%s'\n" "$chezmoi"

  if command -v curl >/dev/null; then
    chezmoi_install_script="$(curl -fsSL get.chezmoi.io)"
  elif command -v wget >/dev/null; then
    chezmoi_install_script="$(wget -qO- get.chezmoi.io)"
  else
    printf >&2 "To install chezmoi, you must have curl or wget installed.\n"
    exit 1
  fi

  sh -c "$chezmoi_install_script" -- -b "$bin_dir"
  unset chezmoi_install_script bin_dir
fi

# POSIX way to get script's dir: https://stackoverflow.com/a/29834779/12156188
script_dir="$(cd -P -- "$(dirname -- "$(command -v -- "$0")")" && pwd -P)"

set -- init --apply --source="$script_dir"

printf >&2 "Running 'chezmoi %s'\n" "$*"
# exec: replace current process with chezmoi
exec "$chezmoi" "$@"
