#!/usr/bin/zsh

if (( $+commands[bat] )); then
  bat() {
    command bat "$@"
  }
elif (( $+commands[batcat] )); then
  bat() {
    command batcat "$@"
  }
fi

mime=$(file -Lbs --mime-type "$1")
category=${mime%%/*}

if [ -d "$1" ]; then
  if (( $+commands[eza] )); then
    eza -1F -sName --group-directories-first --icons --color=always "$1"
  else
    ls -1F --group-directories-first --color=always "$1"
  fi
elif [[ "$category" == "image" ]]; then
  if [[ "$TERM" == "xterm-kitty" ]]; then
    kitten icat "$1"
  elif (( $+commands[chafa] )); then
    chafa -f sixel "$1"
  fi
  if (( $+commands[exiftool] )); then
    exiftool "$1" | bat --color=always -plyaml
  fi
elif [[ "$category" == "text" ]]; then
  bat --color=always -p "$1"
else
  return 1
fi
