#!/bin/sh
# SPDX-FileCopyrightText: 2025 Samuel Wu
#
# SPDX-License-Identifier: 0BSD

if command -v bat >/dev/null; then
  bat() {
    command bat "$@"
  }
elif command -v batcat >/dev/null; then
  bat() {
    command batcat "$@"
  }
fi

mime=$(file -Lbs --mime-type "$1")
category=${mime%%/*}

if [ -d "$1" ]; then
  eza -1F -sName --group-directories-first --icons --color=always "$1"
elif [ "$category" = "image" ]; then
  if [ "$TERM" = "xterm-kitty" ]; then
    kitten icat "$1"
  else
    chafa -f sixel "$1"
  fi
  exiftool "$1" | bat --color=always -plyaml
elif [ "$category" = "text" ]; then
  bat --color=always -p "$1"
else
  return 1
fi
