# SPDX-FileCopyrightText: 2025 Samuel Wu
#
# SPDX-License-Identifier: 0BSD

# Lock the screen after 2mins
# Turn the screen off after 3mins
# Suspend after 5mins
exec swayidle -w \
  timeout 120 'swaylock -f' \
  timeout 180 'swaymsg "output * power off"' \
        resume 'swaymsg "output * power on"' \
  timeout 300 'systemctl suspend' \
  before-sleep 'swaylock -f'
