# SPDX-FileCopyrightText: 2025 Samuel Wu
#
# SPDX-License-Identifier: 0BSD

# Lock the screen after 5mins and turn it off after another 1mins
# Suspend then hibernate after 10mins
exec swayidle -w \
  timeout 300 'swaylock -f' \
  timeout 360 'swaymsg "output * power off"' \
        resume 'swaymsg "output * power on"' \
  timeout 600 'systemctl suspend' \
  before-sleep 'swaylock -f'
