# SPDX-FileCopyrightText: 2026 Samuel Wu
#
# SPDX-License-Identifier: 0BSD

version = "1.1"

["whatrequires"]
type = "command"
attached_command = "repoquery"
descr.C = "Alias for 'repoquery --installed --whatrequires=<package>'"
complete = true

[[whatrequires.required_values]]
value_help.C = "CAPABILITY,..."
descr.C = "Limit to packages that require any of <capabilities>."

[[whatrequires.attached_named_args]]
id_path = "repoquery.installed"

[[whatrequires.attached_named_args]]
id_path = "repoquery.whatrequires"
value="${1}"
