# SPDX-FileCopyrightText: 2025 Samuel Wu
#
# SPDX-License-Identifier: 0BSD

## Set better keybindings
unbind C-b
set -g prefix `
bind ` send-prefix

unbind %
unbind '"'
bind _ split-window -h
bind + split-window -v

bind R source-file ~/.config/tmux/tmux.conf \; \
  display-message "Configuration Reloaded!"

# Set escape delay
set -s escape-time 10

# Set history scroll back
set -g history-limit 9001

# Increase tmux messages display duration from 750ms to 4s
set -g display-time 4000

# Redraw the status bar more frequently
set -g status-interval 5

# Focus events enabled for terminals that support them
set -g focus-events on

# Super useful when using "grouped sessions" and multi-monitor setup
setw -g aggressive-resize on

# Enable mouse support
set -g mouse

# Window renumbering
set -g renumber-windows on

# Enable truecolor
set -as terminal-features ",gnome*:RGB"

# # Install plugins
set -g @plugin 'tmux-plugins/tmux-yank'
set -g @plugin 'azorng/tmux-smooth-scroll'

# Statusbar
set -g @plugin 'uhs-robert/tmux-oasis'

# fzf support
set -g @plugin 'sainnhe/tmux-fzf'
set -g @plugin 'wfxr/tmux-fzf-url'

# Session Management
set -g @plugin 'tmux-plugins/tmux-resurrect'
set -g @plugin 'tmux-plugins/tmux-continuum'

run '$XDG_CONFIG_HOME/tmux/plugins/tpm/tpm'

set -g status-left "#{E:@oasis_module_mode}#{E:@oasis_module_session}#{USER}@#H "
