# SPDX-FileCopyrightText: 2025 Samuel Wu
#
# SPDX-License-Identifier: 0BSD

[opener]
edit = [
  { run = "edit %*", block = true, for = "windows" },
  { run = 'nano "$@"', block = true, for = "unix" },
]
open = [{ run = 'xdg-open "$@"', desc = "Open" }]
play = [
  { run = 'mpv "$@"', orphan = true, for = "unix" },
  { run = 'mpvnet %*', orphan = true, for = "windows" },
]
