" SPDX-FileCopyrightText: 2024 Samuel Wu
"
" SPDX-License-Identifier: 0BSD

set nocompatible

filetype on
filetype plugin on
filetype indent on
syntax on

set ruler
set autoindent
set number
set relativenumber
set laststatus=2
set ignorecase
set viminfofile=~/.cache/viminfo
