#!/usr/bin/env bash
# SPDX-FileCopyrightText: 2025 Samuel Wu
#
# SPDX-License-Identifier: 0BSD

mime=$(file -Lbs --mime-type "$1")
case "$mime" in
inode/directory)
  eza -1F -sName --group-directories-first --icons --color=always "$1"
  ;;
text/* | application/javascript | inode/x-empty)
  if [[ "$1" == *.md ]]; then
    CLICOLOR_FORCE=1 glow -s dark "$1"
  else
    bat --plain --color=always "$1"
  fi
  ;;
image/*)
  if [[ "$TERM" = *kitty* ]]; then
    kitten icat "$1"
  else
    chafa -f sixels "$1"
  fi
  mediainfo --Full "$1"
  ;;
*)
  exit 1
  ;;
esac
