#!/usr/bin/zsh
# SPDX-FileCopyrightText: 2023 mattmc3
# SPDX-FileCopyrightText: 2024 Samuel Wu
#
# SPDX-License-Identifier: MIT
#
# .zshrc - Zsh file loaded on interactive shell sessions.
#

# Show fetch if we are not using VSCode
if [[ "${TERM_PROGRAM}" != "vscode" ]]; then
  fastfetch
fi

# Enable Powerlevel10k instant prompt. Should stay close to the top of .zshrc.
# Initialization code that may require console input (password prompts, [y/n]
# confirmations, etc.) must go above this block; everything else may go below.
if [[ -r "${XDG_CACHE_HOME:-$HOME/.cache}/p10k-instant-prompt-${(%):-%n}.zsh" ]]; then
  source "${XDG_CACHE_HOME:-$HOME/.cache}/p10k-instant-prompt-${(%):-%n}.zsh"
fi

# Set any zstyles you might use for configuration.
[[ ! -f "${ZDOTDIR:-$HOME}/.zstyles" ]] || source "${ZDOTDIR:-$HOME}/.zstyles"

# Clone antidote if necessary.
if [[ ! -d "${ZDOTDIR:-$HOME}/.antidote" ]]; then
  git clone https://github.com/mattmc3/antidote "${ZDOTDIR:-$HOME}/.antidote"
fi

# Create an amazing Zsh config using antidote plugins.
source "${ZDOTDIR:-$HOME}/.antidote/antidote.zsh"
antidote load

# Source anything in .zshrc.d.
for _rc in ${ZDOTDIR:-$HOME}/.zshrc.d/*.zsh; do
  # Ignore tilde files.
  if [[ $_rc:t != '~'* ]]; then
    source "$_rc"
  fi
done
unset _rc

# Set colors for ls, find, grep, etc
export LS_COLORS="$(vivid generate molokai)"

# Use zoxide as replacement for cd
source <(zoxide init zsh --cmd cd)

# To customize prompt, run `p10k configure` or edit .p10k.zsh.
[[ ! -f "${ZDOTDIR:-$HOME}/.p10k.zsh" ]] || source "${ZDOTDIR:-$HOME}/.p10k.zsh"
