#!/bin/zsh
# SPDX-FileCopyrightText: 2023 mattmc3
# SPDX-FileCopyrightText: 2024 Samuel Wu
#
# SPDX-License-Identifier: MIT

#
# .zstyles - Set zstyle settings for plugins that need them.
#

#
# Antidote
#

zstyle ':antidote:bundle' file $ZDOTDIR/.zplugins.txt
zstyle ':antidote:bundle' use-friendly-names 'yes'

#
# FZF-Tab
#

[[ -z "$TMUX" ]] && zstyle ':fzf-tab:*' fzf-command ftb-tmux-popup
zstyle ':completion:*:git-checkout:*' sort false
zstyle ':completion:*:descriptions' format '[%d]'
zstyle ':completion:*' list-colors ${(s.:.)LS_COLORS}
zstyle ':completion:*' menu 'no'
zstyle ':fzf-tab:complete:cd:*' fzf-preview 'eza -1 --color=always $realpath'
zstyle ':fzf-tab:*' fzf-flags --color=fg:1,fg+:2 --bind=tab:accept
zstyle ':fzf-tab:*' use-fzf-default-opts 'yes'
zstyle ':fzf-tab:*' switch-group '<' '>'
