#!/usr/bin/zsh
#
# .zprofile - Zsh file loaded on login.
#

#
# Editors
#

export EDITOR="nano"
export VISUAL="nano"
export PAGER="less"

#
# LESS Preprocessor
#

if [[ -z "$LESSOPEN" ]] && (( $#commands[(i)lesspipe(|.sh)] )); then
  export LESSOPEN="| /usr/bin/env $commands[(i)lesspipe(|.sh)] %s 2>&-"
fi
export LESS="${LESS:--g -i -M -R -S -w -z-4}"

#
# Paths
#

# Ensure path arrays do not contain duplicates.
typeset -gU path fpath cdpath

# Set the list of directories that zsh searches for commands.
path=(
  $HOME/.local/{,s}bin(N)
  /usr/local/{,s}bin(N)
  $path
  $HOME/.dotnet/tools
)

if (( $#commands[snap] )); then
  path=(
    /snap/bin
    $path
  )
fi

fpath=(
  $ZFUNCDIR
  $ZDOTDIR/completions(-/FN)
  $XDG_DATA_HOME/zsh/site-functions
  $fpath
)

# Use `< file` to quickly view the contents of any file.
[[ -z "$READNULLCMD" ]] || READNULLCMD=$PAGER

# OpenSSH
export SSH_AUTH_SOCK=$XDG_RUNTIME_DIR/ssh-agent.socket

# Additional Config Flags
alias wget="${aliases[wget]:-wget} --hsts-file=\$XDG_CACHE_HOME/wget/wget-hsts"
alias gpg="${aliases[gpg]:-gpg} --homedir \"\$GNUPGHOME\""
