#!/usr/bin/zsh
# SPDX-FileCopyrightText: 2023 mattmc3
# SPDX-FileCopyrightText: 2024 Samuel Wu
#
# SPDX-License-Identifier: MIT
#
# .zshenv - Zsh environment file, loaded always.
#

# XDG Base Directories
export XDG_CONFIG_HOME=$HOME/.config
export XDG_DATA_HOME=$HOME/.local/share
export XDG_STATE_HOME=$HOME/.local/state
export XDG_CACHE_HOME=$HOME/.cache
export ZDOTDIR=$XDG_CONFIG_HOME/zsh

# Ensure path arrays do not contain duplicates.
typeset -gU path fpath

# GTK
export GTK2_RC_FILES=$XDG_CONFIG_HOME/gtk-2.0/gtkrc

# GPG
export GNUPGHOME=$XDG_DATA_HOME/gnupg

# Ripgrep
export RIPGREP_CONFIG_PATH=$XDG_CONFIG_HOME/ripgrep/config

# Python
export PYTHON_HISTORY=$XDG_STATE_HOME/python_history

# Dotnet
export DOTNET_CLI_HOME=$XDG_DATA_HOME/dotnet
export DOTNET_CLI_TELEMETRY_OPTOUT=true

export NUGET_PACKAGES=$XDG_CACHE_HOME/NuGetPackages

# npm
export NPM_CONFIG_INIT_MODULE=$XDG_CONFIG_HOME/npm/config/npm-init.js
export NPM_CONFIG_CACHE=$XDG_CACHE_HOME/npm
export NPM_CONFIG_TMP=$XDG_RUNTIME_DIR/npm

# Ensure path arrays do not contain duplicates.
typeset -gU path fpath

# Set the list of directories that zsh searches for commands.
path=(
  $HOME/{,s}bin(N)
  $HOME/.local/{,s}bin(N)
  /usr/local/{,s}bin(N)
  /snap/{,s}bin(N)
  $path
)
