#!/usr/bin/zsh
# SPDX-FileCopyrightText: 2023 mattmc3
# SPDX-FileCopyrightText: 2024 Samuel Wu
#
# SPDX-License-Identifier: MIT
#
# .zshenv - Zsh environment file, loaded always.
#

# XDG Base Directories
export XDG_CONFIG_HOME=$HOME/.config
export XDG_DATA_HOME=$HOME/.local/share
export XDG_STATE_HOME=$HOME/.local/state
export XDG_CACHE_HOME=$HOME/.cache
export ZDOTDIR=$XDG_CONFIG_HOME/zsh

# GTK
export GTK2_RC_FILES=$XDG_CONFIG_HOME/gtk-2.0/gtkrc

# GPG
export GNUPGHOME=$XDG_DATA_HOME/gnupg

# Ripgrep
export RIPGREP_CONFIG_PATH=$XDG_CONFIG_HOME/ripgrep/config

# FZF
export FZF_DEFAULT_OPTS_FILE=$XDG_CONFIG_HOME/fzf/config

# Python
export PYTHON_HISTORY=$XDG_STATE_HOME/python_history

# Dotnet
export DOTNET_CLI_HOME=$XDG_DATA_HOME/dotnet

export DOTNET_CLI_TELEMETRY_OPTOUT=true
export POWERSHELL_TELEMETRY_OPTOUT=true

export NUGET_PACKAGES=$XDG_CACHE_HOME/NuGetPackages

# Nodejs
export NODE_REPL_HISTORY=$XDG_DATA_HOME/node_repl_history

export NPM_CONFIG_USERCONFIG=$XDG_CONFIG_HOME/npm/npmrc

# Rust
export RUSTUP_HOME=$XDG_DATA_HOME/rustup
export CARGO_HOME=$XDG_DATA_HOME/cargo

# Go
export GOPATH=$XDG_DATA_HOME/go
export GOMODCACHE=$XDG_CACHE_HOME/go/mod

# wget
export WGETRC=$XDG_CONFIG_HOME/wgetrc

# Ensure path arrays do not contain duplicates.
typeset -gU path fpath

# Set the list of directories that zsh searches for commands.
path=(
  $HOME/{,s}bin(N)
  $HOME/.local/{,s}bin(N)
  $XDG_DATA_HOME/npm/bin
  /usr/local/{,s}bin(N)
  /snap/{,s}bin(N)
  $path
)
