# SPDX-FileCopyrightText: 2025 Samuel Wu
#
# SPDX-License-Identifier: 0BSD
style:
  tag:
    color: green
    width_percentage: 10
    min_width: 10
  comment:
    color: blue
    width_percentage: 45
    min_width: 20
  snippet:
    color: white
    width_percentage: 45
    min_width: 20

finder:
  command: fzf

client:
  tealdeer: true

shell:
  command: zsh
  finder_command: zsh
